/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-07-24 07:37:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1689666994308L));
    _jspx_dependants.put("jar:file:/C:/green_project/jspworks/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Market/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Welcome~</title>\r\n");
      out.write("<script src=\"/resources/js/memberValidation.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\" integrity=\"sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function checkID(){\r\n");
      out.write("	//alert('test');\r\n");
      out.write("	//ID 중복 확인\r\n");
      out.write("	let mid = $(\"#mid\").val();\r\n");
      out.write("	if(mid == \"\"){\r\n");
      out.write("		alert(\"아이디를 입력해주세요\");\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	//ajax 실행\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type: \"post\",\r\n");
      out.write("		url: \"checkid\",    \r\n");
      out.write("		dataType: \"text\",\r\n");
      out.write("		data: {id: mid},  //서블릿쪽으로 id 보냄\r\n");
      out.write("		success: function(data){ //서블릿에서 응답 받음\r\n");
      out.write("			console.log(data);\r\n");
      out.write("			if($.trim(data)=='usable'){ //$.trim()- 앞,뒤 공백을 없애줌\r\n");
      out.write("				$(\"#btnChk\").attr(\"value\", \"Y\");  //체크 버튼이 눌러짐\r\n");
      out.write("				$(\"#check\").text(\"사용 가능한 ID입니다.\");\r\n");
      out.write("				$(\"#check\").css({\"color\": \"blue\", \"padding\": \"5px 0 0 10px\"});\r\n");
      out.write("			}else{\r\n");
      out.write("				$(\"#check\").text(\"이미 가입된 ID입니다.\");\r\n");
      out.write("				$(\"#check\").css({\"color\": \"red\", \"padding\": \"5px 0 0 10px\"});\r\n");
      out.write("			}\r\n");
      out.write("		},\r\n");
      out.write("		error: function(){\r\n");
      out.write("			alert(\"에러 발생!!\");\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}//checkID 끝\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"container my-3\">\r\n");
      out.write("		<h3 class=\"text-left mx-4 my-4\">회원 가입</h3>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<form action=\"/addMember.do\" method=\"post\" name=\"newMember\">\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label class=\"col-sm-2\">아이디</label>\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<input type=\"text\" name=\"mid\" id=\"mid\" class=\"form-control\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<button type=\"button\" id=\"btnChk\" value=\"N\"\r\n");
      out.write("						   class=\"btn_check btn btn-warning\" onclick=\"checkID()\">ID 확인</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p id=\"check\"></p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label class=\"col-sm-2\">비밀번호</label>\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<input type=\"password\" name=\"passwd1\" class=\"form-control\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label class=\"col-sm-2\">비밀번호 확인</label>\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<input type=\"password\" name=\"passwd2\" class=\"form-control\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label class=\"col-sm-2\">이름</label>\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<input type=\"text\" name=\"mname\" class=\"form-control\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label class=\"col-sm-2\">성별</label>\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<label><input type=\"radio\" name=\"gender\" value=\"male\" checked>남</label>\r\n");
      out.write("						<label><input type=\"radio\" name=\"gender\" value=\"female\" >여</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label class=\"col-sm-2\">생일</label>\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<input type=\"text\" name=\"birthyy\" placeholder=\"년(4자)\" maxlength=\"4\" size=\"6\">\r\n");
      out.write("						<select name=\"birthmm\">\r\n");
      out.write("							<option>월</option>\r\n");
      out.write("						    <option value=\"1\">1</option>\r\n");
      out.write("						    <option value=\"2\">2</option>\r\n");
      out.write("						    <option value=\"3\">3</option>\r\n");
      out.write("						    <option value=\"4\">4</option>\r\n");
      out.write("						    <option value=\"5\">5</option>\r\n");
      out.write("						    <option value=\"6\">6</option>\r\n");
      out.write("						    <option value=\"7\">7</option>\r\n");
      out.write("						    <option value=\"8\">8</option>\r\n");
      out.write("						    <option value=\"9\">9</option>\r\n");
      out.write("						    <option value=\"10\">10</option>\r\n");
      out.write("						    <option value=\"11\">11</option>\r\n");
      out.write("						    <option value=\"12\">12</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<input type=\"text\" name=\"birthdd\" placeholder=\"일\" maxlength=\"2\" size=\"4\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label class=\"col-sm-2\">전화번호</label>\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<input type=\"text\" name=\"phone\" class=\"form-control\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label class=\"col-sm-2\">이메일</label>\r\n");
      out.write("					<div class=\"col-sm-5 my-2\">\r\n");
      out.write("						<input type=\"text\" name=\"email1\" maxlength=\"30\">@\r\n");
      out.write("						<select name=\"email2\">\r\n");
      out.write("							<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("							<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("							<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label class=\"col-sm-2\">주소</label>\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<input type=\"text\" name=\"address\" class=\"form-control\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<div class=\"col-sm-3 my-2\">\r\n");
      out.write("						<input type=\"button\" value=\"가입\" class=\"btn btn-success\"\r\n");
      out.write("							   onclick=\"checkMember()\">\r\n");
      out.write("						<input type=\"reset\" value=\"취소\" class=\"btn btn-secondary\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div><!-- row 끝 -->\r\n");
      out.write("	</div><!-- container 끝 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
